### ISSUE TITLE
Not correct display date

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [dmtrKovalenko/material-ui-pickers#861]
Updated from version 1.x to the latest and now the display of dates is wrong.
I use last version @material-ui/core, react.
The reinstallation of the node_modules gave nothing.

![screenshot_1](https://user-images.githubusercontent.com/12486958/51166550-ff6ca180-18b4-11e9-803a-4d5c96def375.png)

**Comment by dmtrKovalenko** [comment]
You must also update date-fns version and install up-to-date `@date-io/date-fns`

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/q9l2j10wr4?from-embed

**Comment by SergeyWebDeveloper** [comment]
@dmtrKovalenko , install date-fns solved the problem, but now, apart from the current month and year, no other dates are chosen

**Comment by dmtrKovalenko** [comment]
@SergeyWebDeveloper please make sure all dependencies installed the same as in the code sandbox that I sent you later.

**Comment by SergeyWebDeveloper** [comment]
@dmtrKovalenko , thx, problem is solved.

**Comment by iakovosvo** [comment]
Having the same problem. Using these versions:
```
"@date-io/date-fns": "~1.1.0",
"@material-ui/core": "~3.9.1",
"date-fns": "2.0.0-alpha.21",
"material-ui-pickers": "~2.2.4",
```

**Comment by dmtrKovalenko** [comment]
@iakovosvo seems like that your date-fns version still is 1.0.0

**Comment by SergeyWebDeveloper** [comment]
@iakovosvo , The problem was in the date-fns. In the alpha version they have changed API. For example, in version ^2, you need to set the format as yyyy-MM-dd.

**Comment by iakovosvo** [comment]
I have tried that and a bunch of different format combinations but I am still getting gibberish values on the DatePicer. I only get correct values on the input below the label.

**Comment by SergeyWebDeveloper** [comment]
@iakovosvo , show an example of how you do in the sandbox
